version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=4000
  postgres:
    build: ./database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRESS_USER: ${POSTGRESS_USER}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRESS_DB: ${POSTGRESS_DB}
