version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
    networks:
      - my-net
    depends_on:
      - postgres
    environment:
      - PORT=4000
    volumes:
      - ./src:/usr/app/src
    restart: on-failure
  postgres:
    build: ./database
    networks:
      - my-net
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
networks:
  my-net:
    driver: bridge
